title: Randomwalk
description: My Personal Weblogs
author: Rahul Raj
github: https://github.com/rahulrajpl
about: I'm a strange loop. I take randomwalks. 
disqus_shortname: rahulrajpl
google_analytics: UA-146669700-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/rahulrajpl"

share:
  twitter_username: rahulrajpl
  fb_appid: 0192837465raj

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://rahulrajpl.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
